### PR TITLE
english aint Java script. it haz no asi.

### PR DESCRIPTION
**Pull request by sindresorhus**

### CODE REVIEW

**Comment by kevva** [comment]
Tests pls.

**Comment by btford** [comment]
Technically "Automatic Period Insertion." That acronym won't be confusing at all.

**Comment by btford** [comment]
> Tests pls.

+1

**Comment by sindresorhus** [comment]
> Technically "Automatic Period Insertion." That acronym won't be confusing at all.

Nope. Actually: "Automatic Stop Insertion"

**Comment by sindresorhus** [comment]
angry-panda

**Pull request closed without merging**
